# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200622_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=50, null=True, verbose_name='Your username:'),
        ),
    ]
