# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-25 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20200625_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=50, null=True, verbose_name='Your username:'),
        ),
    ]
